version: '3.8'

services:
  app:
    build: .
    container_name: akilli-ajanda-test
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/akilli_ajanda_test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Seyit.2003
      FILE_UPLOAD_DIR: /app/uploads/
    volumes:
      - /Users/seyitkarahan/uploads:/app/uploads
    depends_on:
      - db
    networks:
      - akilli-network

  db:
    image: postgres:16-alpine
    container_name: akilli-ajanda-db-test
    environment:
      POSTGRES_DB: akilli_ajanda_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Seyit.2003
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - akilli-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: akilli-ajanda-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - akilli-network

volumes:
  postgres_data:

networks:
  akilli-network:
    driver: bridge
